version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app-network
    volumes:
      - ./:/usr/src/app
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge  
